services:
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "443:443"
    networks:
      - front_net
      - back_net

  backend:
    build: ./backend
    expose:
      - "5000"
    networks:
      - back_net
    scale: 3

networks:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
